// Generated by CoffeeScript 1.4.0
var Van;

Van = (function() {

  function Van(s) {
    var geometry, material;
    this.dynamicTexture = new THREEx.DynamicTexture(256, 128);
    this.dynamicTexture.context.font = "bolder 90px Verdana";
    geometry = new THREE.CubeGeometry(3, 1, 1.5);
    material = new THREE.MeshPhongMaterial({
      map: this.dynamicTexture.texture
    });
    this.mesh = new THREE.Mesh(geometry, material);
    this.baseLevel = geometry.height / 2;
    this.mesh.position.set(0, geometry.height / 2, 0);
    this.mesh.receiveShadow = true;
    this.mesh.castShadow = true;
    this.dynamicTexture.clear();
    this.dynamicTexture.drawText(s, 32, 64, 'white');
  }

  return Van;

})();
