// Generated by CoffeeScript 1.12.7
var config, engine, hsm, loadingScene;

config = Config.get();

config.fillWindow();

Helper.orientation('landscape');

Persist.PREFIX = 'ce.smackem';

if (Persist.get('guid') == null) {
  Persist.set('guid', Helper.guid());
}

hsm = HighScoreManager.get();

hsm.auth('ldsmackem', 'ldsmackem');

Hodler.reload = function() {
  var gameScene;
  gameScene = Hodler.item('gameScene');
  if (gameScene.readyBaby === true) {
    gameScene.readyBaby = false;
    return Hodler.item('engine').initScene(gameScene);
  }
};

AfterEffects.prototype.effects = function() {
  var effectBloom, effectFilm;
  this.renderModel = new THREE.RenderPass(void 0, void 0);
  effectBloom = new THREE.BloomPass(1.25);
  effectFilm = new THREE.FilmPass(0.15, 0.95, 2048, false);
  effectFilm.renderToScreen = true;
  this.composer = new THREE.EffectComposer(this.engine.renderer);
  this.composer.addPass(this.renderModel);
  this.composer.addPass(effectBloom);
  return this.composer.addPass(effectFilm);
};

engine = Hodler.add('engine', new Engine3D());

Hodler.add('afterEffects', new AfterEffects(engine));

Hodler.add('gameScene', new GameScene());

loadingScene = new RealLoadingScene(["assets/scenes/start.save.json", "assets/logo.png", "assets/mole.json"]);

engine.addScene(loadingScene);

engine.start();
