// Generated by CoffeeScript 1.4.0
var SceneManager;

SceneManager = (function() {
  var PrivateClass, instance;

  function SceneManager() {}

  instance = null;

  PrivateClass = (function() {

    function PrivateClass() {
      this.scenes = [];
      this.index = 0;
    }

    PrivateClass.prototype.addScene = function(scene) {
      return this.scenes.push(scene);
    };

    PrivateClass.prototype.setScene = function(i) {
      var audio, initY, _i, _len, _ref;
      initY = this.scenes[0].player.baseLevel;
      this.scenes[0].player.position.set(0, initY, 0);
      this.scenes[1].player.position.set(0, initY, 0);
      this.scenes[2].player.position.set(0, initY, 0);
      this.scenes[3].player.position.set(0, initY, 0);
      this.scenes[4].player.position.set(0, initY, 0);
      this.scenes[5].player.position.set(0, 2, 0);
      this.scenes[6].player.position.set(0, initY, 0);
      _ref = document.getElementsByTagName("audio");
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        audio = _ref[_i];
        audio.pause();
      }
      audio = document.getElementsByTagName("audio")[i];
      audio.play();
      return this.index = i;
    };

    PrivateClass.prototype.isEmpty = function() {
      return this.scenes.length === 0;
    };

    PrivateClass.prototype.scene = function() {
      return this.scenes[this.index];
    };

    PrivateClass.prototype.tick = function(delta, now) {
      return this.scene().tick(delta, now);
    };

    return PrivateClass;

  })();

  SceneManager.get = function() {
    return instance != null ? instance : instance = new PrivateClass();
  };

  return SceneManager;

})();
