// Generated by CoffeeScript 1.4.0
var Level1,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Level1 = (function(_super) {

  __extends(Level1, _super);

  function Level1() {
    Level1.__super__.constructor.call(this);
    this.player.say(":)");
    this.ground = new Ground();
    this.scene.add(this.ground.mesh);
    this.door = new Door("door");
    this.door.mesh.position.set(0, 0.2, -2);
    this.scene.add(this.door.mesh);
    this.back = new Door("back");
    this.back.mesh.position.set(-1.2, 0.2, 2.2);
    this.scene.add(this.back.mesh);
    this.addSpotlight(1, 2.5, 2);
    this.addSpotlight(-1, 2.5, 2);
  }

  Level1.prototype.tick = function(delta, amount) {
    Level1.__super__.tick.call(this, delta, amount);
    if (keyboard.pressed("space")) {
      if (this.player.mesh.position.distanceTo(this.back.mesh.position) < 0.3) {
        location.reload();
      }
      if (this.player.mesh.position.distanceTo(this.door.mesh.position) < 0.3) {
        return SceneManager.get().setScene(2);
      }
    }
  };

  return Level1;

})(BaseLevel);
