// Generated by CoffeeScript 1.4.0
var Level6,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Level6 = (function(_super) {

  __extends(Level6, _super);

  function Level6() {
    Level6.__super__.constructor.call(this);
    this.player.say(":D");
    this.ground = new Ground();
    this.scene.add(this.ground.mesh);
    this.counter = new Door("19");
    this.counter.mesh.position.set(0, 0.2, -1);
    this.scene.add(this.counter.mesh);
    this.addSpotlight(0, 2.5, 2);
  }

  Level6.prototype.tick = function(delta, amount) {
    var timeLeft;
    Level6.__super__.tick.call(this, delta, amount);
    timeLeft = (parseFloat(this.counter.s) - delta).toFixed(2);
    this.counter.say(timeLeft.toString());
    if (this.counter.mesh.position.distanceTo(this.player.mesh.position) > 2) {
      this.player.jumpCount = 0;
    }
    if (timeLeft < 3) {
      this.player.say(":'(");
      this.spotlights[0].setColor("#ff0000");
    } else {
      if (timeLeft < 6) {
        this.player.say(":(");
        this.spotlights[0].setColor("#fc2500");
      } else {
        if (timeLeft < 9) {
          this.player.say(":|");
          this.spotlights[0].setColor("#f48900");
        } else {
          if (timeLeft < 12) {
            this.player.say(":)");
            this.spotlights[0].setColor("#ebf300");
          }
        }
      }
    }
    if (timeLeft <= 0.8) {
      this.scene.remove(this.spotlights[0].spotLight);
      return this.scene.remove(this.spotlights[0].volumetricSpotlight);
    }
  };

  return Level6;

})(BaseLevel);
