// Generated by CoffeeScript 1.12.7
var MenuScene,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

MenuScene = (function(superClass) {
  extend(MenuScene, superClass);

  function MenuScene() {
    return MenuScene.__super__.constructor.apply(this, arguments);
  }

  MenuScene.prototype.init = function(options) {
    var camera, engine, hammer, light;
    camera = LoadingScene.LOADING_OPTIONS.camera;
    camera.position.set(0, 9, 6);
    camera.lookAt(new THREE.Vector3(0, 2, -2));
    engine = Hodler.item('engine');
    engine.setClearColor('#2d882d');
    this.scene.add(Helper.ambientLight());
    this.scene.add(Helper.ambientLight());
    this.scene.add(Helper.ambientLight());
    light = Helper.pointLight({
      distance: 10
    });
    light.position.set(0, 5, 0);
    this.scene.add(light);
    this.scene.add(this.jmm.clone('mole'));
    hammer = this.jmm.clone('hammer');
    hammer.position.set(4, 0, 0);
    this.hammer = hammer;
    return this.scene.add(hammer);
  };

  MenuScene.prototype.tick = function(tpf) {
    return this.hammer.rotation.x += tpf;
  };

  MenuScene.prototype.doKeyboardEvent = function(event) {
    if (event.type === 'keyup') {
      return;
    }
    return Hodler.item('engine').initScene(Hodler.item('gameScene'));
  };

  MenuScene.prototype.doMouseEvent = function(event, raycaster) {};

  return MenuScene;

})(BaseScene);
